example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

katalog/urls.py
# TODO: Implement Routings Here
from django.urls import path
from katalog.views import show_katalog

app_name = 'katalog'

urlpatterns = [
    path('', show_katalog, name='show_katalog'),
]

mywatchlist/urls.py
from django.urls import path
from mywatchlist.views import show_mywatchlist, show_xml, show_json, show_html
app_name = 'mywatchlist'

urlpatterns = [
    path('', show_mywatchlist, name='show_mywatchlist'),
    path('html/', show_html, name='show_html'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),

]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('katalog/', include('katalog.urls')),
    path('mywatchlist/', include('mywatchlist.urls')),
    path('todolist/', include('todolist.urls')),
    
]

# TODO: Implement Routings Here

todolist/urls.py
from django.urls import path
from todolist.views import add_task, show_todolist_ajax, show_json
from todolist.views import register
from todolist.views import login_user
from todolist.views import logout_user
from todolist.views import create_todo
from todolist.views import status
from todolist.views import delete

app_name = 'todolist'

urlpatterns = [
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('create-task/', create_todo, name="create_todo"),
    path('status/<int:id>/', status, name='status'),
    path('delete/<int:id>/', delete, name='delete'),
    path('json/', show_json, name="show_json"),
    path('add/', add_task, name="add_task"),
    path('', show_todolist_ajax, name='show_todolist_ajax'),
]

example_app/models.py
from django.db import models

# Create your models here.

katalog/models.py
from django.db import models

class CatalogItem(models.Model):
    item_name = models.CharField(max_length=255)
    item_price = models.BigIntegerField()
    item_stock = models.IntegerField()
    description = models.TextField()
    rating = models.IntegerField()
    item_url = models.URLField()

mywatchlist/models.py
from django.db import models

# Create your models here.
from django.db import models

class MyWatchList(models.Model):
    watched = models.BooleanField()
    title = models.TextField()
    rating = models.IntegerField()
    release_date = models.DateField()
    review = models.TextField()

todolist/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.
class Task(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE, null=True, blank=True)
    date = models.DateField(default=timezone.now)
    title = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    is_finished = models.BooleanField(default=False)

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

katalog/views.py
from django.shortcuts import render
from katalog.models import CatalogItem

# TODO: Create your views here.
def show_katalog(request):
    data_barang_katalog = CatalogItem.objects.all()
    context = {
    'list_barang': data_barang_katalog,
    'nama': 'Syifa',
    'id': '2106701066',
}
    return render(request, "katalog.html", context)

    

mywatchlist/views.py
from django.shortcuts import render
from mywatchlist.models import MyWatchList
from django.http import HttpResponse
from django.core import serializers

def show_mywatchlist(request):
    mywatchlist = MyWatchList.objects.all()
    watched = 0
    unwatched = 0
    message = ""

    for movie in mywatchlist:
        if (movie.watched):
            watched += 1
        else:
            unwatched += 1

    if (watched >= unwatched):
        message = "Selamat, kamu sudah banyak menonton!"
    else:
        message = "Wah, kamu masih sedikit menonton!"
    
    context = {
    'list_barang': mywatchlist,
    'nama': 'Syifa',
    'id': '2106701066',
    'message': message
    }
    return render(request, "mywatchlist.html", context)

def show_html(request):
    mywatchlist = MyWatchList.objects.all()
    watched = 0
    unwatched = 0
    message = ""

    for movie in mywatchlist:
        if (movie.watched):
            watched += 1
        else:
            unwatched += 1

    if (watched >= unwatched):
        message = "Selamat, kamu sudah banyak menonton!"
    else:
        message = "Wah, kamu masih sedikit menonton!"
    
    context = {
    'list_barang': mywatchlist,
    'nama': 'Syifa',
    'id': '2106701066',
    'message': message
    }
    return render(request, "mywatchlist.html", context)

# Create your views here.
def show_xml(request):
    data = MyWatchList.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = MyWatchList.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_json_by_id(request, id):
    data = MyWatchList.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = MyWatchList.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

todolist/views.py
import datetime
from django.shortcuts import render
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from todolist.models import Task
from todolist.form import NewForm
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.http import HttpResponse
from django.core import serializers

# Create your views here.
def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Account Successfully Created!')
            return redirect('todolist:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('todolist:show_todolist_ajax')           
        else:
            messages.info(request, 'Wrong Username or Password!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    return redirect('todolist:login')

def create_todo(request):
    if request.method == 'POST':
        form = NewForm(request.POST)
        if form.is_valid():
            task = Task(
                user=request.user,
                title=form.cleaned_data["title"],
                description=form.cleaned_data["description"],
            )
            task.save()
            return redirect("todolist:show_todolist")

    form = NewForm()
    context = {"form": form}
    return render(request, "create_task.html", context)

def status(request, id):
    status = Task.objects.get(pk=id)
    if status.is_finished:
        status.is_finished = False
    else:
        status.is_finished = True
    status.save()
    return HttpResponseRedirect(reverse('todolist:show_todolist_ajax'))

def delete(request, id):
    delete = Task.objects.get(pk=id)
    delete.delete()
    return HttpResponseRedirect(reverse('todolist:show_todolist_ajax'))

@login_required(login_url='/todolist/login/')
def show_todolist_ajax(request):
    data = Task.objects.filter(user=request.user).all()
    context = {
        'todo_list': data,
    } 
    return render(request, "todolist_ajax.html", context)

def show_json(request):
    data = Task.objects.filter(user=request.user).all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def add_task(request):
    if request.method == 'POST':
        title = request.POST.get('title')
        description = request.POST.get('description')
        new_task = Task(
            date=str(datetime.date.today()),
            title=title, 
            description=description,
            user=request.user,
        )
        new_task.save()
    redirect('todolist:show_todolist_ajax')
    return HttpResponse('')
    

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

katalog/templates/katalog.html
{% extends 'base.html' %}

 {% block content %}

  <h1>Lab 1 Assignment PBP/PBD</h1>

  <h5>Name: </h5>
  <p>{{nama}}</p>

  <h5>Student ID: </h5>
  <p>{{id}}</p>

  <table>
    <tr>
      <th>Item Name</th>
      <th>Item Price</th>
      <th>Item Stock</th>
      <th>Rating</th>
      <th>Description</th>
      <th>Item URL</th>
    </tr>
    {% comment %} Add the data below this line {% endcomment %}
    {% for barang in list_barang %}
    <tr>
        <th>{{barang.item_name}}</th>
        <th>{{barang.item_price}}</th>
        <th>{{barang.item_stock}}</th>
        <th>{{barang.rating}}</th>
        <th>{{barang.description}}</th>
        <th>{{barang.item_url}}</th>
    </tr>
{% endfor %}
  </table>

 {% endblock content %}

mywatchlist/templates/mywatchlist.html
{% extends 'base.html' %}

 {% block content %}

  <h1>Tugas 3 Assignment PBP/PBD</h1>

  <h5>Name: </h5>
  <p>{{nama}}</p>

  <h5>Student ID: </h5>
  <p>{{id}}</p>
  <p>{{message}}</p>

  <table>
    <tr>
      <th>Sudah Nonton?</th>
      <th>Judul Film</th>
      <th>Rating</th>
      <th>Tanggal Rilis</th>
      <th>Review</th>
    </tr>
    {% comment %} Add the data below this line {% endcomment %}
    {% for barang in list_barang %}
    <tr>
        <th>{{barang.watched}}</th>
        <th>{{barang.title}}</th>
        <th>{{barang.rating}}</th>
        <th>{{barang.release_date}}</th>
        <th>{{barang.review}}</th>
    </tr>
{% endfor %}
  </table>

 {% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% block content %}
  {% endblock content %}
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.min.js" integrity="sha384-7VPbUDkoPSGFnVtYi0QogXtr74QeVeeIs99Qfg5YCF+TidwNdjvaKZX19NZ/e6oz" crossorigin="anonymous"></script>
</body>

</html>

todolist/templates/create_task.html
{% extends 'base.html' %}

{% block meta %}
<title>Make your TO-DO!</title>
{% endblock meta %}

{% block content %}
<style> 
  input[type=submit] {
    background-color:aquamarine;
    border: none;
    color: rgb(13, 6, 6);
    padding: 16px 32px;
    margin: 4px 2px;
    cursor: pointer;
  }
  input, textarea {
   padding: 0.5rem;
   border: 1px solid;
   border-radius: 8px;
   width: 100%
  }
  ul {
    padding-left: 0.5rem;
    list-style-type: disc;
  }
  body {
    text-align: center;
}
  form {
    display: inline-block;
}
  </style>

<div class="mx-auto container flex flex-col gap-4 pt-8">
  <h1 class="text-4xl font-bold text-center">Make your TODO!</h1>
  <div class="rounded-lg p-4 flex flex-col gap-4 mx-auto bg-base-100">
  <form method="POST" class="m-auto">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
      <tr>
        <td></td>
        <td ><input type="submit" name="submit" value="Create" /></td>
      </tr>
    </table>
  </form>

  {% if messages %}
  <ul class="msg">
    {% for message in messages %}
    <li>{{ message }}</li>
    {% endfor %}
  </ul>
  {% endif %}

</div>

{% endblock content %}

todolist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
<style>
    input[class="btn login_btn"] {
      box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
      transition: 0.3s;
      width: 40%;    
      border-radius: 5px;
      background-color:aquamarine
    }
</style>
{% endblock meta %}


{% block content %}


<div class = "login">

    <h1>Login</h1>

    <form method="POST" action="">
        {% csrf_token %}
        <table>
            <tr>
                <td>Username: </td>
                <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
            </tr>
                    
            <tr>
                <td>Password: </td>
                <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
            </tr>

            <tr>
                <td></td>
                <td><input class="btn login_btn" type="submit" value="Login"></td>
            </tr>
        </table>
    </form>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}     
        
    Don't have an account yet? <a href="{% url 'todolist:register' %}">Create Account</a>
    
</div>

{% endblock content %}

todolist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %}

{% block content %}  

<div class = "login">
    
    <h1>Formulir Registrasi</h1>  

        <form method="POST" >  
            {% csrf_token %}  
            <table>  
                {{ form.as_table }}  
                <tr>  
                    <td></td>
                    <td><input type="submit" name="submit" value="Daftar"/></td>  
                </tr>  
            </table>  
        </form>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}

</div>  

{% endblock content %}

todolist/templates/todolist.html
{% extends 'base.html' %}

{% block meta %}
<title>TODO</title>
<style>
  
  .card {
    box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
    transition: 0.3s;
    width: 40%;    
    border-radius: 5px;
  }
  
  .card:hover {
    transform: scale(1.05);
    box-shadow: 0 10px 20px rgba(0,0,0,.12), 0 4px 8px rgba(0,0,0,.06);    
  }
  
  .container {
    padding: 2px 16px;
  }

  .content {
    padding-left: 20px;
    padding-right: 20px;
}
  .navbar-custom {
    background-color:#F6F6F2;
}
  body {
    background: linear-gradient(-45deg, #388087, #6FB3B8, #BADFE7, #C2EDCE);
    background-size: 400% 400%;
    animation: gradient 15s ease infinite;
    height: 100vh;
  }

  @keyframes gradient {
    0% {
      background-position: 0% 50%;
    }
    50% {
      background-position: 100% 50%;
    }
    100% {
      background-position: 0% 50%;
    }
  }
  
</style>
{% endblock meta %}

{% block content %}
<div class="navbar navbar-custom mb-4">
  <div class="container-fluid justify-content-center">
      <h1 class="navbar-brand" href="#">Hello, {{ user.get_username }}! Here's your to-do list!</h1>
    </div>
  </div>

<div class="content w-100 mx-auto">
  <div class="header text-center mx-auto">
      <a href="{% url 'todolist:logout' %}" class="btn btn-danger" style="float:left">Log Out</a> 
      <a href="{% url 'todolist:create_todo' %}" class="btn btn-primary" style="float:right">Create New Task</a>
  </div>
</div>

<div class="container-fluid">
	<div class="row row-cols-1 row-cols-md-3 g-4 md:justify-end gap-4">
		{% for data in list_todo %}
			<div class="card col-sm-4 mb-1 mt-4 mx-auto" style="width: 18rem;">
				<div class="card-body">
          <h4 class="card-title text-center fw-semibold">{{ data.title }}</h4>
          <ul class="list-group list-group-flush">
            <li class="list-group-item text-secondary">{{ data.date }}</li>
            <li class="list-group-item">{{ data.description }}</li>
          </ul>
				</div>
        <div class="card-footer text-center">
          {% if data.is_finished %}
          <p class="text-success">Finished </p>
          {% else %}
          <p class="text-danger">Not Finished</p>
          {% endif %}
          <button type="button" class="btn btn-dark btn-sm" style="float:left"><a class="text-light" href="{% url 'todolist:delete' data.id %}" style="text-decoration:solid ">Delete</a></button>
          <button type="button" class="btn btn-dark btn-sm" style="float:right"><a class="text-light" href="{% url 'todolist:status' data.id %}" style="text-decoration:solid ">Update</a></button>
        </div>
			</div>
		{% endfor %}
	</div>
</div> 
</div>
<br>

{% endblock content %}

todolist/templates/todolist_ajax.html
{% extends 'base.html' %}

  {% block content %}

  <head>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script>
        function posting(e) {
          e.preventDefault()
          const title = $("#title").val()
          const description = $("#description").val()
          
          const data = {
            title: title,
            description: description,
            csrfmiddlewaretoken: "{{ csrf_token }}"
          }
          
          $.ajax({
            type: 'POST',
            url: '{% url "todolist:add_task" %}',
            data: data, 
            dataType: 'json'
          });

          fetchData();
        }
      
        function update(data) {
          const myElement = $("#main-div")
          myElement.html('');
          for (let i = 0; i < data.length; i++) {
            let message = (data[i].fields.is_finished) ? 'Finished':'Not Finished';
            let color = (data[i].fields.is_finished) ? 'green':'red';
            myElement.append(`
            
              <div class="card col-sm-4 mb-1 mt-4 mx-auto" style="width: 18rem;">
                <div class="card-body">
                  <h4 class="card-title text-center fw-semibold">${data[i].fields.title}</h4>
                  <ul class="list-group list-group-flush">
                    <li class="list-group-item text-secondary">${data[i].fields.date}</li>
                    <li class="list-group-item">${data[i].fields.description}</li>
                  </ul>
                </div>
                <div class="card-footer text-center">
                  <p style="font-weight:bold; color:${color};">${message}</p>
                  <button type="button" class="btn btn-dark" style="float:left;"><a class="text-light" href="status/${data[i].pk}" style="text-decoration:solid ">Update</a></button>
                  <button type="button" class="btn btn-dark" style="float:right;"><a class="text-light" href="delete/${data[i].pk}" style="text-decoration:solid ">Delete</a></button>
                </div>
              </div>
            `)
          }
        }
      
        function fetchData() {
          $.get("/todolist/json", update)
        }
      
        $(document).ready(() => {
          $("#create-button").click(posting)
          fetchData()
        })
    </script>
    <style>
  
        .card {
          box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
          transition: 0.3s;
          width: 40%;    
          border-radius: 5px;
        }
        
        .card:hover {
          transform: scale(1.05);
          box-shadow: 0 10px 20px rgba(0,0,0,.12), 0 4px 8px rgba(0,0,0,.06);    
        }
        
        .container {
          padding: 2px 16px;
        }
      
        .content {
          padding-left: 20px;
          padding-right: 20px;
      }
        .navbar-custom {
          background-color:#F6F6F2;
      }
        body {
          background: linear-gradient(-45deg, #388087, #6FB3B8, #BADFE7, #C2EDCE);
          background-size: 400% 400%;
          animation: gradient 15s ease infinite;
          height: 100vh;
        }
      
        @keyframes gradient {
          0% {
            background-position: 0% 50%;
          }
          50% {
            background-position: 100% 50%;
          }
          100% {
            background-position: 0% 50%;
          }
        }
        
      </style>

  </head>

  <div class="navbar navbar-custom mb-4">
    <div class="container-fluid justify-content-center">
        <h1 class="navbar-brand" href="#">Hello, {{ user.get_username }}! Here's your to-do list!</h1>
      </div>
    </div>
  
  <div class="content w-100 mx-auto">
    <div class="header text-center mx-auto">
        <a href="{% url 'todolist:logout' %}" class="btn btn-danger" style="float:left">Log Out</a> 
        <a data-bs-toggle="modal" href="#addTask" class="btn btn-primary" style="float:right">Add Task</a>
    </div>
  </div>
  
  <div class="row row-cols-1 row-cols-md-3 g-4 md:justify-end gap-4" id="main-div"></div>
  
  <div class="modal fade modal-dialog modal-dialog-centered" id="addTask" tabindex="-1" aria-labelledby="addTaskLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">Add Task</h1>
        </div>
        <div class="modal-body">
          <form method="POST" action="" style="display: inline-block;">
            {% csrf_token %}
            <table>
              <tr>
                <label>Title</label>
                <input type="text" name="title" id="title">
              </tr><br>
              <tr>
                <label>Description</label>
                <input type="textarea" name="description" id="description">
              </tr>
                  <td colspan="2">
                    <input data-bs-dismiss="modal" style="width: 100%; margin-top: 20px; margin-bottom: 7px;" class="btn btn btn-dark" type="submit" name="submit" value="Create" id="create-button">
                  </td>
              </tr>
          </table>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>



 {% endblock content %}